import Head from 'next/head'
import Image from 'next/image'
import styled from "../stitches.config"

const Container = styled('div', {
  maxWidth: 1200,
  margin: 'auto'
})

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h1>Shark Battle</h1>
      </Container>
    </div>
  )
}
